name: Update alexa.netsblox.org to this branch

on:
  push:
    branches:
      - 2934-alexa-integration
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy (alexa.netsblox.org)
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            bash alexa/update-alexa.sh
        if: github.event_name == 'push'

